import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

// components
import Navbar from "./components/Navbar";

const rubik = Rubik({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Next.js Helpdesk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${rubik.className} h-full antialiased`}
    >
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
